package com.model;
// Generated Aug 7, 2018 10:17:20 PM by Hibernate Tools 5.1.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "trainningcrud")
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String subjectId;
	private String subjectName;
	private int hours;
	private Set<Result> results = new HashSet<Result>(0);

	public Subject() {
	}

	public Subject(String subjectId, String subjectName, int hours) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.hours = hours;
	}

	public Subject(String subjectId, String subjectName, int hours, Set<Result> results) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.hours = hours;
		this.results = results;
	}

	@Id

	@Column(name = "subject_id", unique = true, nullable = false, length = 45)
	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "subject_name", nullable = false, length = 45)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "hours", nullable = false)
	public int getHours() {
		return this.hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<Result> getResults() {
		return this.results;
	}

	public void setResults(Set<Result> results) {
		this.results = results;
	}

}
